/**
 * exportSicilyMasks.js
 *
 * Exports binary water-mask GeoTIFFs for the 4 Sicilian reservoirs on selected dates.
 * Dates were selected by select_mask_dates.py: 10 dates per temporal period
 * (2014-2016 and 2022-2024), stratified by area percentile (5th–95th).
 *
 * Pipeline is IDENTICAL to exportGlobalPilotV2.js (which mirrors the app):
 *   - SVM training: 2023 annual composite, JRC occ≥95% water, WorldCover land
 *   - Best orbit selection: highest mean VV pixel coverage, N≥20 filter
 *   - Classification: SVM → gap-fill → filterBounds cleaning (largest intersecting polygon)
 *   - Output band: WaterCleaned (binary 0=land, 1=water) unmasked to remove NoData
 *
 * Output: GeoTIFF per date in Google Drive folder 'GEE_SicilyMasks'
 *   CRS: EPSG:32633 (UTM 33N, appropriate for Sicily)
 *   Scale: 10 m
 *   File naming: mask_{Reservoir}_{YYYY-MM-DD}
 *
 * Paste into GEE Code Editor and click Run (~80 export tasks queued).
 */

// ── Configuration ─────────────────────────────────────────────────────────────
var CFG = {
  s1_start:          '2014-10-01',
  s1_end:            '2026-06-30',
  jrc_occ_thresh:    95,
  jrc_occ_fallback:  80,
  train_year:        2023,
  clean_scale_m:     30,
  max_pixels:        1e9,
  keep_largest_only: false,
  land_ring_inner_m: 500,
  land_ring_outer_m: 2000,
  drive_folder:      'GEE_SicilyMasks',
};

// ── Datasets ──────────────────────────────────────────────────────────────────
var BANDS   = ['VV', 'VH'];
var S1_GRD  = ee.ImageCollection('COPERNICUS/S1_GRD');
var JRC_GSW = ee.Image('JRC/GSW1_4/GlobalSurfaceWater');
var JRC_OCC = JRC_GSW.select('occurrence');
var WC      = ee.ImageCollection('ESA/WorldCover/v200').first().select('Map');
var HYDROLAKES_SIC = ee.FeatureCollection('projects/ee-ciceromartinsjr/assets/HydroLAKES_sicily4');

// ── Sicily reservoirs ─────────────────────────────────────────────────────────
// [name, hylak_id_or_null, lat, lon]
// hylak_id = null  →  coordinate-fallback getLakePoly (Garcia: not in sicily4 asset)
// Poma/Rosamarina/Pozzillo already complete — only Ancipa + Garcia need new exports
var SICILY = [
  ['Ancipa',    1369046,  37.887, 14.565],
  ['Garcia',    null,     37.799, 13.119],
];

// ── Selected dates (output of analysis/select_mask_dates.py) ─────────────────
// 20 dates per reservoir: 10 from 2014-2016 (period A) + 10 from 2022-2024 (period B)
// Stratified by area percentile (5th–95th) within each period.
// Generated by select_mask_dates.py (2026-06-23) — spike-filtered, s1_end=2026-06-30
var SELECTED_DATES = {
  'Poma': [
    '2014-10-31', '2015-08-15', '2016-01-06', '2016-01-30', '2016-05-05',
    '2016-05-17', '2016-10-02', '2016-11-07', '2016-11-13', '2016-12-31',
    '2022-05-22', '2022-09-07', '2023-12-07', '2024-04-17', '2024-08-15',
    '2025-02-23', '2025-09-27', '2026-01-25', '2026-03-08', '2026-06-06',
  ],
  'Rosamarina': [
    '2014-12-01', '2015-02-23', '2015-06-23', '2015-09-03', '2015-11-26',
    '2016-03-13', '2016-04-06', '2016-10-09', '2016-10-21', '2016-12-08',
    '2022-05-29', '2023-02-17', '2023-06-17', '2023-09-21', '2024-07-29',
    '2024-11-02', '2025-04-19', '2025-06-12', '2025-08-17', '2026-05-03',
  ],
  'Pozzillo': [
    '2015-01-18', '2015-06-23', '2015-07-29', '2015-09-03', '2015-11-26',
    '2016-02-18', '2016-04-30', '2016-07-23', '2016-11-02', '2016-11-14',
    '2022-05-17', '2024-01-31', '2024-04-24', '2024-06-23', '2024-08-22',
    '2025-04-07', '2025-08-05', '2025-09-16', '2026-03-15', '2026-06-08',
  ],
  // 10 replacement dates for Ancipa — bad masks removed, stratification corrected
  // Already on disk (skip): 2016-05-12, 2016-07-23, 2016-11-26, 2016-12-26,
  //   2023-08-28, 2024-12-20, 2025-04-19, 2025-09-16, 2026-04-02, 2026-05-15
  'Ancipa': [
    '2015-07-17', '2015-11-14', '2016-03-01', '2016-09-21', '2016-10-15',
    '2016-10-21',
    '2023-10-27', '2025-01-01', '2025-11-21', '2026-01-14',
  ],
  // Garcia — Period B only (no Period A masks yet; export SAR area via exportGlobalPilotV2.js
  // with ['Garcia', 37.799, 13.119, null, 42123, 380, null] to get 2014-2016 area series first)
  // 10 dates stratified by area (96–382 ha range), selected by select_mask_dates.py 2026-06-24
  'Garcia': [
    '2014-11-30', '2014-12-24', '2015-02-22', '2015-09-26', '2015-10-20', 
    '2016-03-12', '2016-05-23', '2016-11-01', '2016-11-19', '2016-12-25', 
    '2022-07-03', '2022-09-25', '2023-01-11', '2024-02-23', '2025-06-29', 
    '2025-08-22', '2025-08-28', '2025-12-20', '2026-04-13', '2026-04-20',
  ],
};

// ── getLakePoly — mirrors exportGlobalPilotV2.js ──────────────────────────────
// hylakId != null → look up in HydroLAKES_sicily4 asset (Poma/Rosamarina/Pozzillo/Ancipa)
// hylakId === null → coordinate fallback using lat/lon point (Garcia: not in sicily4 asset)
function getLakePoly(hylakId, lat, lon) {
  var jrcMax    = JRC_GSW.select('max_extent').eq(1).selfMask();
  var searchArea;
  if (hylakId !== null) {
    var hydroGeom = HYDROLAKES_SIC
      .filter(ee.Filter.eq('Hylak_id', hylakId)).first().geometry();
    searchArea = hydroGeom.buffer(2000);
  } else {
    searchArea = ee.Geometry.Point([lon, lat]).buffer(3000);
  }
  var waterVecs = jrcMax.reduceToVectors({
    geometry: searchArea, scale: 30, maxPixels: 1e9,
    bestEffort: true, geometryType: 'polygon',
    eightConnected: true, tileScale: 4,
  });
  return waterVecs.sort('count', false).first().geometry();
}

// ── selectBestOrbit — identical to exportGlobalPilotV2.js ─────────────────────
function selectBestOrbit(col, aoi) {
  var withOrbit = col.map(function(img) {
    return img.set({
      '_relOrbit': img.getNumber('relativeOrbitNumber_start'),
      '_pass':     img.getString('orbitProperties_pass'),
    });
  });
  var orbits = withOrbit.aggregate_array('_relOrbit').distinct();
  var scored = ee.FeatureCollection(orbits.map(function(o) {
    var sub  = withOrbit.filter(ee.Filter.eq('_relOrbit', o));
    var n    = sub.size();
    var pass = ee.String(sub.first().get('_pass'));
    var cov  = sub.map(function(img) {
      var count = img.reduceRegion({
        reducer: ee.Reducer.count(), geometry: aoi,
        scale: 100, maxPixels: 1e7, bestEffort: true,
      }).getNumber('VV');
      return img.set('_cov', count);
    }).aggregate_mean('_cov');
    return ee.Feature(null, {'orbit': o, 'pass': pass, 'n': n, 'cov': cov});
  }));
  var qualified  = scored.filter(ee.Filter.gte('n', 20));
  var candidates = ee.Algorithms.If(qualified.size().gt(0), qualified, scored);
  var best       = ee.FeatureCollection(candidates).sort('cov', false).first();
  return col.filter(ee.Filter.and(
    ee.Filter.eq('relativeOrbitNumber_start', best.getNumber('orbit')),
    ee.Filter.eq('orbitProperties_pass',      best.getString('pass'))
  ));
}

// ── classifyImage — identical to exportGlobalPilotV2.js ───────────────────────
function classifyImage(img, svm, lakePoly) {
  var aoi = lakePoly.buffer(100);

  var water  = img.select(BANDS).classify(svm).eq(1).clip(aoi).rename('Water');
  var mask   = water.unmask(0).clip(aoi);
  var dist   = mask.fastDistanceTransform(30).clip(aoi);
  var filled = dist.lte(0.5).updateMask(dist.lte(0.5))
                   .where(mask, 1).rename('WaterFilled');

  var polys = filled.reduceToVectors({
    geometryType: 'polygon',
    reducer:      ee.Reducer.countEvery(),
    scale:        CFG.clean_scale_m,
    maxPixels:    CFG.max_pixels,
    bestEffort:   true,
    tileScale:    4,
  });

  // Keep polygons that physically intersect lakePoly (not centroid-inside, which
  // fails for elongated valley reservoirs where the dam body centroid falls outside
  // the JRC max-extent polygon).  Among intersecting polys, keep the largest.
  var intersecting = polys.filterBounds(lakePoly);
  var keptPolys    = ee.FeatureCollection(ee.Algorithms.If(
    intersecting.size().gt(0),
    ee.FeatureCollection([intersecting.map(function(f) {
      return f.set('_area', f.geometry().area({maxError: 1}));
    }).sort('_area', false).first()]),
    ee.FeatureCollection([polys.map(function(f) {
      return f.set('_area', f.geometry().area({maxError: 1}));
    }).sort('_area', false).first()])
  ));

  var keptMask = ee.Image(0).paint({featureCollection: keptPolys, color: 1});
  var cleaned  = filled.updateMask(keptMask).rename('WaterCleaned');

  return cleaned;
}

// ── Main loop ─────────────────────────────────────────────────────────────────
SICILY.forEach(function(res) {
  var rName   = res[0];
  var hylakId = res[1];
  var lat     = res[2];
  var lon     = res[3];
  var dates   = SELECTED_DATES[rName];

  var lakePoly = getLakePoly(hylakId, lat, lon);
  var aoi      = lakePoly.buffer(100);
  var trainClip = aoi.buffer(CFG.land_ring_outer_m);

  // ── Training composite (2023) ────────────────────────────────────────────
  var s1Composite = S1_GRD
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.eq('resolution_meters', 10))
    .filterBounds(trainClip)
    .filter(ee.Filter.calendarRange(CFG.train_year, CFG.train_year, 'year'))
    .select(BANDS)
    .mosaic()
    .focal_mean(30, 'circle', 'meters')
    .clip(trainClip);

  // ── Water samples ────────────────────────────────────────────────────────
  var waterStrict = JRC_OCC.gte(CFG.jrc_occ_thresh).selfMask().sample({
    region: lakePoly, scale: 30, numPixels: 500, seed: 42, geometries: true,
  }).map(function(f) { return f.set('landcover', 1); });

  var waterFallback = JRC_OCC.gte(CFG.jrc_occ_fallback).selfMask().sample({
    region: lakePoly, scale: 30, numPixels: 500, seed: 42, geometries: true,
  }).map(function(f) { return f.set('landcover', 1); });

  var waterSamples = ee.FeatureCollection(
    ee.Algorithms.If(waterStrict.size().gt(10), waterStrict, waterFallback)
  );

  // ── Land samples ─────────────────────────────────────────────────────────
  var landRing = lakePoly.buffer(CFG.land_ring_outer_m)
                   .difference(lakePoly.buffer(CFG.land_ring_inner_m));
  var landMask = WC.neq(80).and(WC.neq(90)).and(WC.neq(95))
    .and(JRC_OCC.unmask(0).eq(0)).selfMask();
  var landSamples = landMask.sample({
    region: landRing, scale: 30, numPixels: 500, seed: 42, geometries: true,
  }).map(function(f) { return f.set('landcover', 2); });

  // ── Train SVM ────────────────────────────────────────────────────────────
  var trainedSamples = s1Composite.select(BANDS).sampleRegions({
    collection: waterSamples.merge(landSamples),
    properties: ['landcover'],
    scale:      30,
  }).filter(ee.Filter.inList('landcover', ee.List([1, 2])))
    .filter(ee.Filter.notNull(BANDS));

  var svm = ee.Classifier.libsvm({
    kernelType: 'RBF',
    cost:        1,
    gamma:       0.01,
  }).train({
    features:        trainedSamples,
    classProperty:   'landcover',
    inputProperties: BANDS,
  });

  // ── Best orbit (same orbit as area CSV exports) ───────────────────────────
  var s1col = S1_GRD
    .filterBounds(aoi)
    .filterDate(CFG.s1_start, CFG.s1_end)
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.eq('resolution_meters', 10))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
    .select(BANDS)
    .map(function(img) {
      return img.focal_mean(30, 'circle', 'meters')
        .copyProperties(img, ['system:time_start', 'orbitProperties_pass',
                              'relativeOrbitNumber_start', 'angle']);
    });

  var bestCol = selectBestOrbit(s1col, aoi);

  // ── Export one GeoTIFF per selected date ─────────────────────────────────
  dates.forEach(function(dateStr) {
    var d0  = ee.Date(dateStr);
    // bestCol already filtered to one orbit → first() gives the single daily image.
    // Avoid .mosaic().copyProperties() chain: copyProperties returns ee.Element,
    // which has no .select() — causing "img.select is not a function".
    var img = ee.Image(bestCol.filterDate(d0, d0.advance(1, 'day')).first());

    var cleaned = classifyImage(img, svm, lakePoly);

    // unmask so exported GeoTIFF has explicit 0s (land) rather than NoData
    var maskOut = cleaned.unmask(0).toByte();

    Export.image.toDrive({
      image:       maskOut,
      description: 'mask_' + rName + '_' + dateStr,
      folder:      CFG.drive_folder,
      fileNamePrefix: 'mask_' + rName + '_' + dateStr,
      region:      lakePoly.buffer(300),
      scale:       10,
      crs:         'EPSG:32633',
      maxPixels:   1e9,
    });
  });

  print('Queued ' + dates.length + ' mask exports: ' + rName);
});
