"""Emit the LaTeX longtable (Table 1) of the global-pilot reservoirs.

Columns: ID, Reservoir, Country, Climate zone (Koppen-Geiger descriptor), Area, A/P.
Set = the JRC-scored reservoirs in biome_kge.csv (N varies as the pipeline is
refined; do not hardcode it here). Country/area/climate from
global_pilot_v4_candidates.csv. Sorted by static A/P. The ID column (continent
prefix + running number, from gen_reservoir_ids.py/reservoir_ids.csv) is the
label used for this reservoir in Figures 4/5/7/8, so a reader can trace a
plotted point back to its name/country/climate here.
"""
import os
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "manuscript", "sections", "table_pilot.tex"))

df = pd.read_csv(os.path.join(HERE, "biome_kge.csv"))[["name", "ap_m", "climate_zone"]].copy()
cand = pd.read_csv(os.path.join(HERE, "global_pilot_v4_candidates.csv"))
cand = cand.drop_duplicates("name").set_index("name")
df["country"] = df.name.map(cand["country"])
df["area_km2"] = df.name.map(cand["area_ha_approx"]) / 100.0
# a few originals may miss the candidate row -> fill from climate/known
df["country"] = df["country"].fillna("--")
df = df.sort_values("ap_m").reset_index(drop=True)

ids = pd.read_csv(os.path.join(HERE, "reservoir_ids.csv"))[["name", "id"]].set_index("name")
df["id"] = df.name.map(ids["id"])
if df["id"].isna().any():
    raise SystemExit(f"WARN missing ID for: {df[df['id'].isna()].name.tolist()}")

miss = df[df.area_km2.isna()].name.tolist()
if miss:
    print("WARN missing area:", miss)
print("rows:", len(df), "| climate zones:", df.climate_zone.nunique())

def areastr(a):
    return "--" if pd.isna(a) else "%.1f" % a
rows = "\n".join(
    "%s & %s & %s & %s & %s & %.0f \\\\" % (
        r["id"], r["name"].replace("_", " "), r["country"], r["climate_zone"],
        areastr(r["area_km2"]), r["ap_m"])
    for _, r in df.iterrows())

tex = ("% Auto-generated by analysis/gen_pilot_table.py -- do not edit by hand.\n"
       r"\begingroup\footnotesize" "\n"
       r"\begin{longtable}{@{}l l l l r r@{}}" "\n"
       r"\caption{The __N__ global-pilot reservoirs, ordered by static shoreline" "\n"
       r"area-to-perimeter ratio (A/P). Area is the approximate full-pool surface;" "\n"
       r"climate is the K\"oppen--Geiger zone. ID is the continent-coded label" "\n"
       r"(E=Europe, A=Africa, As=Asia, Am=Americas, O=Oceania) used for this" "\n"
       r"reservoir in Figures~\ref{fig:ap_curve}, \ref{fig:fourway}, \ref{fig:eecu}" "\n"
       r"and \ref{fig:wind}.}" "\n"
       r"\label{tab:pilot}\\" "\n"
       r"\toprule" "\n"
       r"ID & Reservoir & Country & Climate zone & Area (\si{\kilo\metre\squared}) & A/P (m) \\" "\n"
       r"\midrule").replace("__N__", str(len(df))) + "\n" + r"""
\endfirsthead
\multicolumn{6}{@{}l}{\itshape Table~\ref{tab:pilot} (continued)}\\
\toprule
ID & Reservoir & Country & Climate zone & Area (\si{\kilo\metre\squared}) & A/P (m) \\
\midrule
\endhead
\midrule
\multicolumn{6}{r@{}}{\itshape continued on next page}\\
\endfoot
\bottomrule
\endlastfoot
""" + rows + "\n\\end{longtable}\n\\endgroup\n"

open(OUT, "w", encoding="utf-8").write(tex)
print("saved ->", OUT)
